apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlops-model
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mlops
  template:
    metadata:
      labels:
        app: mlops
    spec:
      containers:
      - name: model
        image: mlops-model
        ports:
        - containerPort: 5000
